#!/bin/bash

z=`vserver-stat |grep '^[0-9]' | grep -v "^0 " | awk '{print $1"-"$8}'`
totalrecv=0
totalsend=0
echo "----------------------------------------"
printf "|       user |       recv |       send |\n"
echo "----------------------------------------"
for p in  $z;do
    ctx=`echo $p | cut -d- -f1`;
    user=`echo $p | cut -d- -f2`;
    send=`cat /proc/virtual/$ctx/cacct | grep INET: | awk '{print $3}' | cut -d/ -f2`
    recv=`cat /proc/virtual/$ctx/cacct | grep INET: | awk '{print $2}' | cut -d/ -f2`
    totalrecv=$(($totalrecv + $recv))
    totalsend=$(($totalsend + $send))
    printf "| %10s | %8dmb | %8dmb |\n" $user $(($recv/1024/1024)) $(($send/1024/1024))
done
echo "----------------------------------------"
printf "|      total | %8dgb | %8dgb |\n" $(($totalrecv/1024/1024/1024)) $(($totalsend/1024/1024/1024))
echo "----------------------------------------"

