#!/bin/sh
openvpn_root="/etc/openvpn/"

if [ ! $1 ]; then
echo usage $0 CN;
exit
fi;
if [ -d $openvpn_root/client/$1 ]; then
echo this cn alredy exists
exit
fi;

if [ ! -d $openvpn_root"client" ]; then
mkdir $openvpn_root"client"
fi;

user_root=$openvpn_root"client/$1/"
mkdir $user_root
name=$1

openssl req -subj "/countryName=US/stateOrProvinceName=NA/organizationName=OpenVPN/CN="$name -nodes -new  -keyout "$user_root"client.key -out "$user_root"client.csr -days 3650 -batch -config "$openvpn_root"openvpn_openssl.conf   > /dev/null 2>&1
openssl ca  -subj "/countryName=US/stateOrProvinceName=NA/organizationName=OpenVPN/CN="$name -outdir "$openvpn_root"keys/ -keyfile "$openvpn_root"ca.key -cert "$openvpn_root"ca.crt -out "$user_root"client.crt -in "$user_root"client.csr -days 3650 -batch -config "$openvpn_root"openvpn_openssl.conf  > /dev/null  2>&1
cp $openvpn_root"ca.crt" $user_root
echo "установить openvpn-gui с http://openvpn.se/download.html Installation Package (Both 32-bit and 64-bit TAP driver included)
после установки, vpn.ovpn, ca.crt, client.crt client.key помещаем в директорию C:\Program Files\OpenVPN\config\ " >  $user_root/readme.txt
ip=`ifconfig | grep "inet addr:" | head -n1 | awk '{print $2}' | awk -F: '{print $2}'`
if [ `echo $ip | wc -l` ]; then
ip=`ifconfig | grep "inet" | grep netmask | head -n1 | awk '{print $2}'`
fi;
echo "
remote $ip
port 1666
proto tcp
dev tun
tun-mtu 1500
client
keepalive 60 120
tls-client
auth SHA1
ns-cert-type server
ca \"ca.crt\" 
cert \"client.crt\"
key \"client.key\"
cipher AES-256-CBC
redirect-gateway
comp-lzo
verb 0
" >> $user_root"vpn.ovpn"
