#!/bin/bash
BASE=`vgdisplay  2>&1 | grep "VG Name" | awk '{print $3}'`
if [[ ! -d /var/lib/vservers ]];then
    echo '[e] vserver not found'
    exit
fi
if [[ ! -d /vs ]];then
    ln -s /var/lib/vservers /vs
fi
if [[ ! -d /vservers ]];then
    ln -s /var/lib/vservers /vservers
fi
if [ $# != 3 ];then
echo "usage user G ip"
exit
fi

function check {
    $1 > /dev/null 2>&1
    if [ $? != 0 ];then
        echo failure by $1
        exit
    fi
}
ping -c 1 -W 1 $3  > /dev/null 2>&1
if [ $? == 0 ];then
    echo ip $3 already UP
    exit
fi

if [ -d /etc/vservers/$1 ];then
    echo already exists user $1
    exit
fi

if [ ! -f /dev/$BASE/$1 ];then
    check "lvcreate -L${2}G -n $1 $BASE"
    check "mkfs.xfs /dev/$BASE/$1"
fi

if [ ! -d /vservers/$1 ];then
    check "mkdir /vservers/$1"
    echo "/dev/$BASE/$1    /vservers/$1   xfs   noatime       0       1" >> /etc/fstab
    check "mount -a"
fi

if [ "`uname -m`" == "x86_64" ];then
    export ARCH=amd64;  
else 
    export ARCH=i386;
fi

vserver $1 build  --force -m debootstrap -n$1 --hostname $1 \
--flags lock,nproc,ulimit,sched_prio,virt_load,virt_cpu,virt_uptime,virt_mem \
--interface "eth0:$3"  -- -d squeeze

echo "deb http://mirror.yandex.ru/debian/ squeeze main contrib non-free" > /vservers/$1/etc/apt/sources.list
echo "default" > /etc/vservers/$1/apps/init/mark
sed 's/.\+tmpfs.\+//g'  /etc/vservers/$1/fstab -i
mkdir /etc/vservers/$1/rlimits;
echo "500000" > /etc/vservers/$1/rlimits/rss;
echo "2.6.30" > /etc/vservers/$1/uts/release;
echo "Linux" > /etc/vservers/$1/uts/sysname;
echo "Daedalus.ru" > /etc/vservers/$1/uts/version;
ln -fs /usr/share/zoneinfo/Europe/Moscow /vservers/$1/etc/localtime
vserver $1 start;
vsomething -q  vserver $1 -- exec apt-get update;


